swagger: "2.0"
info:
  description: "This is a sample PLG Web server."
  version: 0.0.1
  title: "PLG Web"
  contact:
    email: "andbur@dtu.dk"
host: "localhost:8080"
basePath: "/api/v2/"
schemes:
  - "http"
paths:
  /system/ping:
    get:
      tags:
        - "system"
      summary: "Ping the system"
      description: "Checks if the system is online"
      produces:
        - "text/plain"
      parameters: []
      responses:
        "200":
          description: "The system is up and running"
  /process/randomize:
    get:
      tags:
        - "processes"
      summary: "Generate a random process"
      description: "Generate a random process specification using the default parameters."
      produces:
        - "application/json"
      parameters: []
      responses:
        "200":
          description: "The process has been correctly generated"
          schema:
            $ref: "#/definitions/Process4Web"
  /process/plg2bpmn:
    post:
      tags:
        - "processes"
      summary: "Converts a process to BPMN"
      description: ""
      produces:
        - "application/xml"
      parameters:
        - in: "body"
          name: "plg"
          description: "The process specification"
          required: true
          schema:
            $ref: "#/definitions/Process4Web"
      responses:
        "200":
          description: "The process has been correctly converted"
  /process/plg2tpn:
    post:
      tags:
        - "processes"
      summary: "Converts a process to Petri net as TPN file"
      description: ""
      produces:
        - "text/plain"
      parameters:
        - in: "body"
          name: "plg"
          description: "The process specification"
          required: true
          schema:
            $ref: "#/definitions/Process4Web"
      responses:
        "200":
          description: "The process has been correctly converted"
  /process/plg2pnml:
    post:
      tags:
        - "processes"
      summary: "Converts a process to Petri net as PNML file"
      description: ""
      produces:
        - "application/xml"
      parameters:
        - in: "body"
          name: "plg"
          description: "The process specification"
          required: true
          schema:
            $ref: "#/definitions/Process4Web"
      responses:
        "200":
          description: "The process has been correctly converted"
  /process/plg2dot:
    post:
      tags:
        - "processes"
      summary: "Converts a process to a Graphviz dot BPMN file"
      description: ""
      produces:
        - "text/plain"
      parameters:
        - in: "body"
          name: "plg"
          description: "The process specification"
          required: true
          schema:
            $ref: "#/definitions/Process4Web"
      responses:
        "200":
          description: "The process has been correctly converted"
          
  /streamer/status/{processName}:
    get:
      tags:
      - "streamer"
      summary: "Checks if a process is being streamed"
      description: ""
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "processName"
        type: "string"
        description: "The id of the process to be verified for streaming"
        required: true
      responses:
        "200":
          description: "Whether the process is being streamed or not"
          schema:
            type: "boolean"
  
  /streamer/start/{processName}:
    post:
      tags:
      - "streamer"
      summary: "Starts streaming the given process"
      description: ""
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "processName"
        type: "string"
        description: ""
        required: true
      - in: "body"
        name: "plg"
        description: "The process specification"
        required: true
        schema:
          $ref: "#/definitions/Process4Web"
      - in: "query"
        name: "broker"
        type: "string"
        format: "hostname"
        description: "The host of the broker where to publish the events"
        required: true
      - in: "query"
        name: "topic"
        type: "string"
        description: "The base topic name"
        required: true
      responses:
        "200":
          description: "Whether the stream started to be streamed or not"
          schema:
            type: "boolean"
        
          
definitions:
  Process4Web:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
        description: "A short name for the process"
      serialization:
        type: "string"
        description: "A string serialization of the process (can the XML generated from PLG)."
      serializationType:
        type: "string"
        description: "The current serialization type."
        enum:
          - "plg"
